services:
  postgres:
    hostname: postgres
    image: postgres:14.7
    command: ["postgres", "-c", "log_statement=all"]
    environment:
      POSTGRES_USER: postgres
      POSTGRES_PASSWORD: postgres
      POSTGRES_HOST: postgres
      POSTGRES_PORT: 5432
      POSTGRES_DB: postgres
  cube:
    image: cubejs/cube:latest
    ports:
      - 4001:4000
      - 15432:15432
    environment:
      CUBEJS_DEV_MODE: true
      CUBEJS_DB_TYPE: postgres
      CUBEJS_DB_HOST: postgres
      CUBEJS_DB_NAME: postgres
      CUBEJS_DB_USER: postgres
      CUBEJS_DB_PASS: postgres
    volumes:
      - .:/cube/conf